'''
Enoncé :


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
list_fib = []
list_fib.append(1)
list_fib.append(2)
print(list_fib)
print(len(list_fib))
print(list_fib[len(list_fib)-1])

x = 0

while x <= 4000000:
    n = len(list_fib)
    x = list_fib[n-1] + list_fib[n-2]
    print(x)
    list_fib.append(x)

sum = 0
for elem in list_fib:
    if elem%2 == 0:
        sum += elem
print('final')
print(list_fib)
print(sum)